### ISSUE TITLE
`types` may be is null or undefined in `generateTypeDefinition`

### ISSUE THREAD

**Issue by vhexl** [Theaninova/vite-plugin-kaitai#2]
If the `.ksy` file has no *User-defined types* `types` key, an error will occur

```
11:00:20 AM [vite] Internal server error: Cannot convert undefined or null to object
  Plugin: vite-plugin-kaitai
  File: /workspaces/EFlash-Tool/src/components/ksys/eflash/baseinfo.ksy
      at Function.entries (<anonymous>)
      at generateTypeDefinition (/workspaces/EFlash-Tool/node_modules/vite-plugin-kaitai/lib/kaitai-type-generator.js:28:19)
      at TransformContext.generateTypes (/workspaces/EFlash-Tool/node_modules/vite-plugin-kaitai/lib/kaitai-type-generator.js:21:119)
      at async Object.importYaml (/workspaces/EFlash-Tool/node_modules/vite-plugin-kaitai/lib/yaml-importer.js:24:9)
      at async TransformContext.compileKaitaiToJs (/workspaces/EFlash-Tool/node_modules/vite-plugin-kaitai/lib/kaitai-compiler.js:11:18)
      at async TransformContext.transform (/workspaces/EFlash-Tool/node_modules/vite-plugin-kaitai/lib/index.js:25:23)
      at async Object.transform (file:///workspaces/EFlash-Tool/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30)
      at async loadAndTransform (file:///workspaces/EFlash-Tool/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29)
      at async viteTransformMiddleware (file:///workspaces/EFlash-Tool/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:59342:32)
``

**Comment by Theaninova** [comment]
https://github.com/Theaninova/vite-plugin-kaitai/blob/6d675212aed9bfb1188670c941e4e21a43e2e996/src/kaitai-type-generator.ts#L32 This is what you're talking about right? If so, a fix should be as easy as 
```diff

-    ...Object.entries(spec.types).map(([name, type]) => toInterface(name, type)),

+    ...Object.entries(spec.types ?? {}).map(([name, type]) => toInterface(name, type)),
```

**Comment by vhexl** [comment]
Yes, I tried changing it in `node_modules/vite-plugin-kaitai/lib/kaitai-type-generator.js` and it worked fine,

This vite plugin is awesome!

**Comment by Theaninova** [comment]
https://www.npmjs.com/package/vite-plugin-kaitai/v/1.0.3
